name: exercise

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-unused-top-binds

default-extensions:
  - BlockArguments
  - LambdaCase

dependencies:
  - base

executables:
  exercise:
    source-dirs: .
    main: Main.hs
